title: "Tim Searle"
description: >-
  A personal journal sharing my opinions on the technology industry, my project statuses and learnings from my journey as a software engineer.
baseurl: ""
url: "https://www.searle.dev"

# Social
twitter_username: timsearle_
github_username:  timsearle
linkedin_username: timsearleuk
instagram_username: climbingtim

plugins:
  - jekyll-feed
show_excerpts: true

header_pages:
  - about.md

lang: en
locale: en_GB

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - .ruby-version
  - .gitignore
  - .idea
  - .github
  - vendor
  - scripts
  - AGENT.md

liquid:
  error_mode: strict
#  strict_variables: true
  strict_filters: true
